//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.18 at 04:48:06 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "com/whitetest/soap/data/models", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.whitetest.soap.data.models;
